### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by LCsee** [zyqz97/Aerial_lifting#8]
你好，在复现longhua2数据，运行bash/3_2_cross_view_process.sh遇到了错误

在gp_nerf/datasets/dataset_utils.py  get_rgb_index_mask_depth_dji_instance_crossview 函数中 keep_mask = metadata.load_mask()返回为None，后续代码使用torch.ones()对其赋值。在load_mask()函数中，注意到load_mask为空，该路径是必须的吗，想知道该问题是如何产生的，非常感谢！

以下是报错信息：
{
  "message": {
    "message": "RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.",
    "extraInfo": {
      "py_callstack": "Traceback (most recent call last):\n  File \"/root/miniconda3/envs/aeriallift/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 345, in wrapper\n    return f(*args, **kwargs)\n  File \"/mnt/common_storage/luchuanchuan/Aerial_lifting/gp_nerf/train.py\", line 64, in main\n    Runner(hparams).train()\n  File \"/mnt/common_storage/luchuanchuan/Aerial_lifting/gp_nerf/runner_gpnerf.py\", line 495, in train\n    for dataset_index, item in enumerate(data_loader):\n  File \"/root/miniconda3/envs/aeriallift/lib/python3.9/site-packages/torch/utils/data/dataloader.py\", line 521, in __next__\n    data = self._next_data()\n  File \"/root/miniconda3/envs/aeriallift/lib/python3.9/site-packages/torch/utils/data/dataloader.py\", line 561, in _next_data\n    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration\n  File \"/root/miniconda3/envs/aeriallift/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py\", line 49, in fetch\n    data = [self.dataset[idx] for idx in possibly_batched_index]\n  File \"/root/miniconda3/envs/aeriallift/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py\", line 49, in <listcomp>\n    data = [self.dataset[idx] for idx in possibly_batched_index]\n  File \"/mnt/common_storage/luchuanchuan/Aerial_lifting/gp_nerf/datasets/memory_dataset_depth_dji_instance_crossview_process.py\", line 164, in __getitem__\n    depth_next[inf_mask] = depth_next[~inf_mask].max()\nRuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.\n",
      "timestamp": "1728896300"
    }
  }
}
Traceback (most recent call last):
  File "/mnt/common_storage/luchuanchuan/Aerial_lifting/gp_nerf/train.py", line 68, in <module>
    main(_get_train_opts())
  File "/root/miniconda3/envs/aeriallift/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/mnt/common_storage/luchuanchuan/Aerial_lifting/gp_nerf/train.py", line 64, in main
    Runner(hparams).train()
  File "/mnt/common_storage/luchuanchuan/Aerial_lifting/gp_nerf/runner_gpnerf.py", line 495, in train
    for dataset_index, item in enumerate(data_loader):
  File "/root/miniconda3/envs/aeriallift/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/aeriallift/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda3/envs/aeriallift/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/aeriallift/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/common_storage/luchuanchuan/Aerial_lifting/gp_nerf/datasets/memory_dataset_depth_dji_instance_crossview_process.py", line 164, in __getitem__
    depth_next[inf_mask] = depth_next[~inf_mask].max()
RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.

**Comment by LCsee** [comment]
不好意思，先前的描述有误，是在load_mask()函数中self._mask_path为空

**Comment by xxxxzp** [comment]
您好 您配置的conda环境是严格按照作者所描述的内容创建的吗

**Comment by LCsee** [comment]
非常感谢回复，我将关闭这个issue
